language: node_js
sudo: required
dist: trusty
services:
  - docker
  - rabbitmq
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm install -g greenkeeper-lockfile@1
before_script:
  - sudo apt-get update && sudo apt-get install nodejs npm
  - sudo docker-compose -f ./docker-compose.yml up -d
  - greenkeeper-lockfile-update
script:
  - docker exec -it poet_frost-api-build npm run coverage
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - COMMIT_HASH=$(git log -1 --pretty=%h)
  - REPO="poetapp/frost-api"
  - TAG_HASH=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "${COMMIT_HASH}"; else echo "v-${COMMIT_HASH}-beta"; fi)
  - TAG_BRANCH=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi)
  - docker cp poet_frost-api-build:/usr/src/app/api/dist ./api_dist
  - docker cp poet_frost-api-build:/usr/src/app/api/node_modules ./api_node_modules
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t ${REPO}:${TAG_HASH} . || travis_terminate 1
  - docker tag ${REPO}:${TAG_HASH} ${REPO}:${TAG_BRANCH}
  - if [ -n "$TRAVIS_TAG" ]; then docker tag ${REPO}:${TAG_HASH} ${REPO}:"$TRAVIS_TAG"; fi
  - docker push ${REPO}
