language: node_js
node_js:
 - "9.4.0"
before_install:
  - npm install -g greenkeeper-lockfile@1
services:
  - docker
  - rabbitmq
before_script:
  - greenkeeper-lockfile-update
  - cd ./Docker && sudo docker-compose up -d && cd ..
  - npm run build
  - npm run start:ci > /dev/null 2>&1 &
  - git clone git@github.com:poetapp/node.git
  - cd ./node
  - sudo make ipfs
  - sleep 5
  - npm install
  - npm run build
  - npm start > /dev/null 2>&1 &
  - cd ..
script:
  - npm run lint
  - npm run test:integration
after_script:
  - greenkeeper-lockfile-upload
