language: node_js
sudo: required
dist: trusty
services:
  - docker
  - rabbitmq
env:
  - REPO=poetapp/frost-api
before_script:
  - sudo docker-compose -f ./docker-compose.yml up -d
script:
  - docker exec -it poet_frost-api-build npm run coverage
before_deploy:
  - bash ./scripts/docker-build.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - bash ./scripts/docker-push.sh
    on:
      all_branches: true
after_deploy:
  - npm run travis-deploy-once "npm run semantic-release"
