language: minimal

notifications:
  slack:
    on_success: change
    on_failure: always
    on_error: always
    on_cancel: always
    rooms:
      secure: "Hk9fXXRZdbB7m3+3KUsaGqG0Z91rff/XYTG/0x9HIK1o4Jj9BD2rYCA8YuUDEnq1PQU70ITX/heq8cnkqCtJAV0rhwQEKzcMyBlqWN4LPrzYGpcK0E8OymOvs6bKNhozhKW8g5D7p7eV5Y0H6EpqvtZflMRDe/7/fc+gz+5QLXLgw0lEnFtsp9j481At8+RVJSwxJA154Pf7JFpoHFwuiZwEseAjxVHL+z/aKzBQhAbTLx5r230XgLf6YDGjEB9O0wRZR9e01BJnl4tf3yq3KDAho/0D24nbZe3d+j6TXrdX8imh4iSDZhbkYc21+WzDUxjde772Ee7mWY/FFbcjsXKu0qtBiKyRmXmf/MdG/nPrcUcGrUcp+uf5lzIfi7K2dDeW5Wdu91bUqXFpQCfgMxMmvGT9TI+1jryItS1w39DPMe9nDUamXhqfA1kQm4OnkWMBbig6dWb/pMb2clGanfZU9X9VSY2OE4jcIhUBvJiuSltY8XFCUR6aMssta1AdAgBg2vQZfa7DDyu3NIdvUcPLMyQbHb4QF0QrHCXmrh2CtmAqNasecoLpp/v58akAjFBXqMFI2nSNA+m8AF0pLQwR4SNKyLq7L/g9g9s/hQt3O7olvoXZ1DIAiTcFi96IJbRl5+9XVHZJCHvcJ2Llb8YTSt3l4M+lwjNU/SiLQQY="

services:
  - docker

env:
  REPO: poetapp/frost-api
  DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
install:
  - docker-compose up -d
  - sleep 10
script:
  - docker-compose exec frost-api npm run lint
  - docker-compose exec frost-api npm run coverage
after:
  - docker images
before_deploy:
  - bash ./scripts/docker-build.sh
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash ./scripts/docker-push.sh
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script:
      - docker-compose exec frost-api npx semantic-release --no-ci
    on:
      branch: master
