version: '2'
services:
  vault:
    container_name: "vault"
    image: vault:0.8.3
    stdin_open: true
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=goldfish
    cap_add:
        - IPC_LOCK
    command: server -dev
    ports:
      - "8200:8200"

  goldfish:
    container_name: "goldfish"
    build:
      context: ./goldfish
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "8000:8000"
    links:
      - vault
    depends_on:
      - vault
    command: /app/entrypoint.sh

  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
