version: '2'
services:
  consul:
    image: "consul:1.2.2"
    container_name: "poet_consul"
    hostname: "consul"
    volumes:
      - ./config/consul:/usr/share/consul
      - ./tools/consul.sh:/consul.sh
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    entrypoint: /consul.sh

  vault:
    image: "vault:0.11.1"
    container_name: "poet_vault"
    hostname: "vault"
    links:
      - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    depends_on:
      - consul
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh
      - ./config/vault:/config
      - ./config/vault/policies:/policies
    entrypoint: /wait-for-it.sh -h consul -p 8500 -t 30 -- vault server -config=/config/vault.hcl

  mongodb:
      image: "mongo:3.4"
      container_name: "poet_mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - "27017:27017"
      command: mongod --smallfiles --logpath=/dev/null # --quiet

  ipfs:
      image: "ipfs/go-ipfs:latest"
      container_name: "poet_ipfs"
      ports:
          - "8080:8080"
          - "4001:4001"
          - "5001:5001"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"

  poet-node:
      image: "poetapp/node:latest"
      container_name: "poet_node"
      ports:
          - "18080:18080"
      depends_on:
          - mongodb
          - ipfs
      links:
        - mongodb:mongodb
        - rabbitmq:rabbitmq
        - ipfs:ipfs
      volumes:
          - ./tools/wait-for-rabbit.sh:/usr/src/app/wait-for-rabbit.sh
      environment:
          - POET_SERVICE=node
          - RABBITMQ_URL=amqp://rabbitmq
          - MONGODB_URL=mongodb://mongodb:27017/poet
          - IPFS_URL=http://ipfs:5001
      command: "./wait-for-rabbit.sh -h rabbitmq -p 5672 -t 30 -- npm start"

  maildev:
      image: "djfarrelly/maildev"
      container_name: "maildev"
      ports:
        - "1025:1025"
        - "1080:1080"
      command: bin/maildev --web 1080 --smtp 1025
