version: '2'
services:
  consul:
    image: "consul"
    hostname: "consul"
    volumes:
      - ./config/consul:/usr/share/consul
      - ./tools/consul.sh:/consul.sh
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    entrypoint: /consul.sh

  vault:
    depends_on:
      - consul
    image: "vault"
    hostname: "vault"
    links:
      - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh
      - ./config/vault:/config
      - ./config/vault/policies:/policies
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/vault.hcl

  mongodb:
      image: mongo:3.4
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
